# Generated by Django 5.1.2 on 2024-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='home_screen_tags',
            field=models.TextField(default=''),
        ),
    ]
