# Generated by Django 5.1.2 on 2024-10-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_api_key_alter_account_home_screen_tags'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('videos', models.ManyToManyField(related_name='playlists', to='page.video')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='watch_later',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.playlist'),
        ),
    ]
