# Generated by Django 5.1.2 on 2024-10-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_playlist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
