# Generated by Django 5.1.2 on 2024-10-18 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_playlist_owner_remove_playlist_videos'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='watch_later',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist'),
        ),
        migrations.DeleteModel(
            name='PlayList',
        ),
    ]
