# Generated by Django 5.1.2 on 2024-10-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscriber_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
