# Generated by Django 5.1.2 on 2024-10-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_description_channel_subscriber_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile_picture',
            field=models.URLField(default=''),
        ),
    ]
