# Generated by Django 5.1.2 on 2024-10-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channel_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='profile_picture',
            new_name='profile_medium',
        ),
        migrations.AddField(
            model_name='channel',
            name='profile_high',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='profile_small',
            field=models.URLField(default=''),
        ),
    ]
