# Generated by Django 5.1.2 on 2024-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_rename_profile_picture_channel_profile_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='playlist_id',
            field=models.TextField(default=''),
        ),
    ]
