# Generated by Django 5.1.2 on 2024-10-18 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_remove_playlist_owner_remove_playlist_videos'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='account.account')),
                ('videos', models.ManyToManyField(related_name='playlists', to='page.video')),
            ],
        ),
    ]
